site_name: BookBrainz User Guide
theme:
  name: custommill
  main_color: '#754e37'
  toc_depth: 10
  home: home
  include_search_page: true
  locale: en
  highlightjs: true
# These are configuration options for the custommill theme.
# See https://siphalor.github.io/mkdocs-custommill/#customization/~extra-configuration-options
extra:
  logo: 'images/BookBrainz_logo_bw.svg'
  article_nav_top: false
markdown_extensions:
  toc:
    toc_depth: '2-6'
  footnotes: